name: Release
on:
  push:
    # Run only when a new Git tag is pushed
    tags:
      - 'v*' # Trigger on tags that start with 'v', like v1.0.0
permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all history (including tags) for GoReleaser to work correctly
          fetch-depth: 0

      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Use your desired Go version

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest # Use the latest version of GoReleaser
          args: release --clean # The command to execute
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
